"""
Generate a PR description for an SME-authored case.

The PR description includes:
  - Case summary (title, ID, file, outcome, branch)
  - SME attestation block (typed attestation + credentials)
  - Validator report (which validators passed, which warned, any failures)
  - Integrity-test result (PASS / FAIL from test_runner)
  - Companion-doc updates (CASE_PROVENANCE row, EVALUATION_COVERAGE bump)
  - Generated-by footer

The SME's attestation is embedded as a markdown block so a reviewer can
see exactly what was attested and by whom. This is the audit-trail
artifact that satisfies CASE_AUTHORING_GUIDE.md § 11 Phase 1 SME review
when there is no separate clinical-reviewer comment.
"""

from __future__ import annotations

from dataclasses import dataclass

from pacca.agents.sme_authoring.models import (
    CaseDraftResponse,
    ValidationOutcome,
    ValidationReport,
)


@dataclass(frozen=True)
class PRMetadata:
    """Auxiliary metadata that the SME provides at PR-creation time."""

    sme_attestation: str
    target_file: str
    is_new_file: bool
    integrity_test_passed: bool
    integrity_test_summary: str = ""


def render_pr_title(case: CaseDraftResponse) -> str:
    """One-line PR title under 80 chars."""
    short_title = case.title[:60].rstrip()
    if len(case.title) > 60:
        short_title += "..."
    return f"sme-cases: add {case.case_id} — {short_title}"


def render_pr_body(
    case: CaseDraftResponse,
    metadata: PRMetadata,
    validator_reports: list[ValidationReport],
) -> str:
    """
    Build the full PR description as a markdown string.

    The structure intentionally mirrors what reviewers expect from
    PACCA's existing case PRs (see PR #9 description format).
    """
    sections = [
        _render_summary(case, metadata),
        _render_attestation(metadata.sme_attestation),
        _render_validator_report(validator_reports),
        _render_integrity_result(metadata),
        _render_companion_docs(case, metadata),
        _render_footer(),
    ]
    return "\n\n".join(sections)


def _render_summary(case: CaseDraftResponse, metadata: PRMetadata) -> str:
    file_note = (
        f"NEW FILE: `{metadata.target_file}`"
        if metadata.is_new_file
        else f"`{metadata.target_file}`"
    )
    return (
        "## Summary\n\n"
        f"- **Case ID:** {case.case_id}\n"
        f"- **Title:** {case.title}\n"
        f"- **Target file:** {file_note}\n"
        f"- **Diagnosis:** {case.diagnosis_code} — {case.diagnosis_description}\n"
        f"- **Procedure:** {case.procedure_code} — {case.procedure_description}\n"
        f"- **Expected outcome:** `{case.expected_outcome}`\n"
        f"- **Expected branch:** `{case.expected_branch}`"
    )


def _render_attestation(attestation: str) -> str:
    return (
        "## SME attestation\n\n"
        "> **Attested by SME (Phase 1 review per `docs/CASE_AUTHORING_GUIDE.md` § 11):**\n"
        ">\n"
        f"> {attestation}"
    )


def _render_validator_report(reports: list[ValidationReport]) -> str:
    if not reports:
        return "## Validator report\n\n(no validators ran)"

    rows = []
    for report in reports:
        if report.outcome == ValidationOutcome.PASS:
            marker = "✓ PASS"
        elif report.outcome == ValidationOutcome.WARN:
            marker = "⚠ WARN"
        else:
            marker = "✗ FAIL"
        reason = report.reason or "(no detail)"
        rows.append(f"| `{report.validator}` | {marker} | {reason} |")

    table = "| Validator | Outcome | Detail |\n|---|---|---|\n" + "\n".join(rows)
    blocking = sum(1 for r in reports if r.is_blocking)
    summary = f"\n\n**Summary:** {len(reports)} validators ran, {blocking} blocking failures."
    return f"## Validator report\n\n{table}{summary}"


def _render_integrity_result(metadata: PRMetadata) -> str:
    if metadata.integrity_test_passed:
        line = "✓ Integrity tests PASS after write."
    else:
        line = "✗ Integrity tests FAILED — see below."
    summary = (
        f"\n\n```\n{metadata.integrity_test_summary.strip()}\n```"
        if metadata.integrity_test_summary
        else ""
    )
    return f"## Integrity test result\n\n{line}{summary}"


def _render_companion_docs(case: CaseDraftResponse, metadata: PRMetadata) -> str:
    return (
        "## Companion-doc updates\n\n"
        f"- `docs/CASE_PROVENANCE.md`: added row for {case.case_id}\n"
        f"- `docs/EVALUATION_COVERAGE.md`: bumped header table "
        f"(per-file count + Total live)\n"
        f"- Per-cell matrices (Dimensions 1-8): NOT updated; deferred per the "
        f"doc's own re-baseline schedule."
    )


def _render_footer() -> str:
    return (
        "---\n\n"
        "Generated by `pacca sme-author` (SMECaseAuthoringAgent v1.0).\n"
        "See `docs/CASE_AUTHORING_GUIDE.md` for the authoring contract."
    )
