from enum import Enum

class AuthorizationStatus(str, Enum):
    PENDING = "PENDING"
    INFORMATION_NEEDED = "INFORMATION_NEEDED"
    IN_REVIEW = "IN_REVIEW"
    AUTO_APPROVED = "AUTO_APPROVED"
    DENIED = "DENIED"
    CANCELLED = "CANCELLED"

class EvidenceSourceType(str, Enum):
    LAB_RESULT = "LAB_RESULT"
    MEDICATION_HISTORY = "MEDICATION"
    CLINICAL_NOTE = "CLINICAL_NOTE"
    PATIENT_REPORTED = "PATIENT_REPORTED"

class ComplexityLevel(str, Enum):
    ROUTINE = "ROUTINE"
    INTERMEDIATE = "INTERMEDIATE"
    COMPLEX = "COMPLEX"
    CRITICAL = "CRITICAL"

class ReviewTier(str, Enum):
    AUTOMATED = "AUTOMATED"
    MEDICAL_DIRECTOR_AGENT = "MEDICAL_DIRECTOR_AGENT"
    HUMAN = "HUMAN"
